config/routes.rb
Gadgets::Application.routes.draw do
  root 'gadgets#index'
  resources :gadgets do
    collection do
      post :view_as_table
      post :view_as_thumbnails
    end
    resources :images
  end
  resource :users
  resource :sessions

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :user
  has_many :images

  validates :name, presence: true

  private
    # NOTE: Allows to search for both `name` and `description` fields.
    def prepare_search_text
      self.search = (name + ' ' + description).downcase
    end
    before_save :prepare_search_text
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gadget

  has_attached_file :image, :styles => {:thumbnail => "200x200>", :icon => "50x50>" }
  validates :image, :attachment_presence => true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gadgets

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true

  # NOTE: Using hashes instead of raw passwords.
  def self.signin name, password
    return false if name.blank? or password.blank?
    User.find_by name: name, password: Digest::MD5.hexdigest(password)
  end

  def self.signup name, password
    return false if name.blank? or password.blank?
    user = User.new
    user.name = name
    user.password = Digest::MD5.hexdigest password
    user.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def current_user
      @_current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
    helper_method :current_user

    def require_signin
      redirect_to new_sessions_path unless current_user
    end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :require_signin

  def new
    @gadget = current_user.gadgets.build
  end

  def show
    @gadget = current_user.gadgets.find params[:id], include: :images
  end

  def index
    if (@query = params[:query]).present?
      @gadgets = current_user.gadgets.where('search LIKE ?', "%#{@query.downcase}%") \
      .all include: :images
    else
      @gadgets = current_user.gadgets.all include: :images
    end
  end

  def create
    @gadget = current_user.gadgets.build gadget_params

    if @gadget.save
      redirect_to @gadget
    else
      render 'new'
    end
  end

  def edit
    @gadget = current_user.gadgets.find params[:id]
  end

  def update
    @gadget = current_user.gadgets.find params[:id]

    if @gadget.update gadget_params
      redirect_to @gadget
    else
      render 'edit'
    end
  end

  def view_as_table
    session[:view] = 'table'
    redirect_to root_path
  end

  def view_as_thumbnails
    session[:view] = 'thumbnails'
    redirect_to root_path

  end

  def destroy
    @gadget = current_user.gadgets.find params[:id]
    @gadget.destroy

    redirect_to :back
  end

  private
    def gadget_params
      params.require(:gadget).permit(:name, :description)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_signin

  def create
    @gadget = current_user.gadgets.find params[:gadget_id]
    @image = @gadget.images.create(image_params)
    redirect_to :back
  end

  def destroy
    @gadget = current_user.gadgets.find params[:gadget_id]
    @image = @gadget.images.find params[:id]
    @image.destroy
    redirect_to :back
  end

  private
    def image_params
      params.require(:image).permit(:image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user = User.signin(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @user = User.new
      @user.name = params[:name]
      @user.valid?
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if User.signup(params[:name], params[:password])
      redirect_to new_sessions_path
    else
      @user = User.new
      @user.name = params[:name]
      @user.valid?
      render 'new'
    end
  end
end

app/views/gadgets/_as_table.html.erb
<table class="table gadgets-table">
  <% @gadgets.each do |gadget| %>
    <tr>
      <td>
        <% if gadget.images.size > 0 %>
          <% image = gadget.images[0] %>
          <%= link_to gadget do %>
            <div class="gadget-image-icon">
              <div class="gadget-image-outer-icon">
                <img src="<%= image.image.url(:icon) %>"></img>
              </div>
            </div>
          <% end %>
        <% else %>
          &nbsp;
        <% end %>
      </td>
      <td class="nowrap"><%= link_to gadget do %><%= gadget.name %><% end %></td>
      <td><%= gadget.description %></td>
      <td>
        <%= link_to gadget, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </td>
    </tr>
  <% end%>
</table>

app/views/gadgets/_as_thumbnails.html.erb
<div class="gadgets-as-thumbnails">
  <% @gadgets.each do |gadget| %>
    <div class="gadget-image-with-name">
      <%= link_to gadget, method: :delete, class: "gadget-image-remove", data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>

      <%= link_to gadget do %>
        <div class="gadget-image-with-name-outer">
          <% if gadget.images.size > 0 %>
            <% image = gadget.images[0] %>
            <img src="<%= image.image.url(:thumbnail) %>"></img>
          <% end %>
        </div>
        <p class="gadget-image-name"><%= gadget.name %></p>
      <% end %>
    </div>
  <% end%>
</div>

app/views/gadgets/_form.html.erb
<%= form_for @gadget, html: {class: "form-horizontal", role: "form"} do |f| %>

  <div class="form-group <%= 'has-error' if @gadget.errors.messages[:name] %>">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @gadget.errors.messages[:description] %>">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <!-- <div class="form-group">
    <%= f.label :images, class: "col-sm-2 control-label" %>
    <%= f.file_field :image, class: "fix-file-input" %>
  </div> -->

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if @gadget.new_record? %>
        <%= link_to 'Back', gadgets_path, class: "btn btn-default", role: "button" %>
        <button type="submit" class="btn btn-primary">Create</button>
      <% else %>
        <%= link_to 'Back', gadget_path(@gadget), class: "btn btn-default", role: "button" %>
        <button type="submit" class="btn btn-primary">Update</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/gadgets/_no_results.html.erb
<div class="jumbotron">
  No Gadgets matching '<%= @query %>' query.
</div>

app/views/gadgets/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome <%= current_user.name %></h1>
  <p>
    This application allow you to manage your Gadgets.<br/>
    Seems like there's no one yet, why not create one?
  </p>
  <p>
    <%= link_to 'Create...', new_gadget_path, role: 'button', class: 'btn btn-lg btn-primary' %>
  </p>
</div>

app/views/gadgets/edit.html.erb
<h1>Edit Gadget</h1>

<br/>

<%= render 'form' %>

app/views/gadgets/index.html.erb
<% if @gadgets.empty? %>
  <% if @query.blank? %>
    <%= render 'welcome' %>
  <% else %>
    <%= render 'no_results' %>
  <% end %>
<% else %>
  <% if session[:view] == 'thumbnails' %>
    <%= render 'as_thumbnails' %>
  <% else %>
    <%= render 'as_table' %>
  <% end %>
<% end %>

app/views/gadgets/new.html.erb
<h1>Create new Gadget</h1>

<br/>

<%= render 'form' %>

app/views/gadgets/show.html.erb
<%= link_to edit_gadget_path(@gadget), class: "edit-button btn btn-default" do %>
  <span class="glyphicon glyphicon-pencil"></span>
<% end %>

<h1><%= @gadget.name %></h1>
<p><%= @gadget.description %></p>

<div class="clearfix">
  <% @gadget.images.each do |image| %>
    <div class="gadget-image">
      <%= link_to [@gadget, image], class: 'gadget-image-remove', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>

      <div class="gadget-image-outer">
        <img src="<%= image.image.url(:thumbnail) %>"></img>
      </div>
    </div>
  <% end %>
</div>

<% if @gadget.images.empty? %>
  <p>No images, create one</p>
<% end %>

<div>
  <%= form_for [@gadget, @gadget.images.build] do |f| %>
    <%= f.file_field :image, onchange: "document.getElementById('new_image').submit();" %>
  <% end %>
</div>

app/views/layouts/_buttons.html.erb
<%= link_to new_gadget_path, class: "btn btn-primary navbar-btn navbar-left", role: "button", title: "Add Gadget" do %>
  <span class="glyphicon glyphicon-plus"></span>
<% end %>

<div class="btn-group navbar-btn">
  <% active = session[:view] == 'thumbnails' ? '' : 'active' %>
  <%= link_to view_as_table_gadgets_path, method: 'post', class: "btn btn-default #{active}", role: 'button' do %>
    <span class="glyphicon glyphicon-th-list"></span>
  <% end %>

  <% active = session[:view] == 'thumbnails' ? 'active' : '' %>
  <%= link_to view_as_thumbnails_gadgets_path, method: 'post', class: "btn btn-default #{active}", role: 'button' do %>
    <span class="glyphicon glyphicon-th"></span>
  <% end %>
</div>

<form action="<%= gadgets_path %>" class="navbar-form navbar-left" method="get" role="search">
  <div class="form-group">
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search" %>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Gadgets</title>

    <!-- Styles. -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <!-- Navigation. -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">My Gadgets</a>
        </div>
        <div class="navbar-collapse collapse">
          <%= render "layouts/buttons" %>
          <%= render "users/navigation_form" %>
        </div>
      </div>
    </div>

    <!-- Content. -->
    <div class="container">
      <%= yield %>
    </div>

    <!-- Putting JS down to speedup content loading. -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form-horizontal", role: "form"} do |f| %>

  <div class="form-group <%= 'has-error' if @user.errors.messages[:name] %>">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @user.errors.messages[:password] %>">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if @user.new_record? %>
        <button type="submit" class="btn btn-primary">Sign in</button>
      <% else %>
        <button type="submit" class="btn btn-primary">Sign up</button>
      <% end %>
    </div>
  </div>

<% end %>

app/views/users/_navigation_form.html.erb
<% if current_user %>
  <%= form_tag sessions_path, method: 'delete', class: "navbar-form navbar-right user-form", role: "form" do %>
    <button type="submit" class="btn btn-success">Sign out</button>
  <% end %>
  <p class="navbar-text navbar-right">Signed in as <%= current_user.name %></p>
<% else %>
  <!-- <%= form_tag sessions_path, class: "navbar-form", role: "form" do %>
    <div class="form-group">
      <%= text_field_tag :name, '', class: "form-control", placeholder: "Name" %>
    </div>
    <div class="form-group">
      <%= password_field_tag :password, '', class: "form-control", placeholder: "Password" %>
    </div>
    <button type="submit" class="btn btn-success">Sign in</button>
    <%= link_to 'Sign up', new_users_path, class: "btn btn-default", role: "button" %>
  <% end %> -->
  <div class="navbar-right">
    <%= link_to 'Sign in', new_sessions_path, class: "btn btn-default navbar-btn", role: "button" %>
    <%= link_to 'Sign up', new_users_path, class: "btn btn-default navbar-btn", role: "button" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<br/>

<%= form_tag users_path, class: "form-horizontal", role: "form" do %>

  <div class="form-group <%= 'has-error' if @user.errors.messages[:name] %>">
    <%= label_tag :name, nil, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= text_field_tag :name, params[:name], class: "form-control" %>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @user.errors.messages[:password] %>">
    <%= label_tag :password, nil, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= password_field_tag :password, '', class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Sign up</button>
    </div>
  </div>

<% end %>